services:
  tb2_unizar:
    image: tb2_unizar
    build:
      context: ./docker/
      dockerfile: Dockerfile
    container_name: tb2_unizar
    environment:
      DISPLAY: $DISPLAY
      ROS_LOCALHOST_ONLY: 0
      ROS_DOMAIN_ID: 3
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      TURTLEBOT3_MODEL: wafffle
      GAZEBO_MODEL_PATH: /opt/ros/jazzy/share/turtlebot3_gazebo/models

    privileged: true
    volumes:
      # X11
      - ~/.Xauthority:/root/.Xauthority
      # 
      - /dev/:/dev
      
      # By default, mount the current directory. Change to the line below for development
      - ./tb2_unizar:/root/tb2_unizar_ws/src/tb2_unizar
      # - ./drones_unizar_dev_ws:/root/drones_unizar_dev_ws
    network_mode: "host"
    command: tail -f /dev/null
