services:
  tb2_unizar:
    image: tb2_unizar
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: tb2_unizar
    environment:
      DISPLAY: $DISPLAY
      ROS_DOMAIN_ID: 3
      TURTLEBOT3_MODEL: waffle
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      GAZEBO_MODEL_PATH: /opt/ros/jazzy/share/turtlebot3_gazebo/models
      CYCLONEDDS_URI: file:///root/tb2_unizar_ws/src/tb2_unizar/cyclonedds.xml

    privileged: true
    volumes:
      # X11
      - ~/.Xauthority:/root/.Xauthority
      # 
      - /dev/:/dev
      
      # By default, mount the current directory (Option 1 in README.md). Change to the line below for development (Option 2 in README.md)
      - ./tb2_unizar:/root/tb2_unizar_ws/src/tb2_unizar
      - ./ros_ws:/root/ros_ws
      - ./monitor:/root/monitor
      - venv_data:/root/monitor/venv       # ★ venv separado dentro del contenedor
    network_mode: "host"
    command: tail -f /dev/null

volumes:
  venv_data: {} 