urg_node:
  ros__parameters:
    # ip_address: "192.168.0.10"
    # ip_port: 10940
    serial_port: "/dev/ttyACM0"
    serial_baud: 115200
    laser_frame_id: base_laser_link
    angle_max: 1.5707963
    angle_min: -1.5707963
    publish_intensity: false
    publish_multiecho: false
    calibrate_time: false
    default_user_latency: 0.0
    diagnostics_tolerance: 0.05
    diagnostics_window_time: 5.0
    error_limit: 4
    get_detailed_status: false
    cluster: 0
    skip: 1